### ISSUE TITLE
Can only add one camera manualy to Homey on 1.1.26

### ISSUE THREAD

**Issue by mattiassvahn** [AdyRock/com.onvif#16]
Hi if a add one camera (fully working) and the try to add another camera with new ip i get [duplicate_device] error. If i remove the firs one, then no problem adding the other camera. but same issue when try to add the first one.

**Comment by AdyRock** [comment]
Sorry, I have only just seen the message so I'm not why I didn't get notified.
Anyway, thank you for pointing out the issue and I think I have found the cause. I will publish an update ASAP.

**Comment by AdyRock** [comment]
Hmm, what I thought might have been the problem was false.
I have updated the app in the store https://homey.app/en-gb/app/com.onvif/ONVIF-Camera/test/
This has more diagnostics when adding devices. To enable them go to More > Apps > ONVIF > Configure App and set the LOG LEVEL to Basic Information.
Then add the two cameras so you see the error. Finally go back to the log and tap on Send Log.

Thanks for your patience and I hope we can solve the issue quickly.
