### ISSUE TITLE
Camera refresh

### ISSUE THREAD

**Issue by Rockhoppers1964** [AdyRock/com.onvif#3]
Installed app and it found and connected to cameras fine. Set up a couple of flows and all good getting snapshots and pushing them to user.
Issue comes when i look at the camera using the device page, the picture shown is from when the app was installed and does not refresh even when you press the refresh icon below the picture.

Used a flow this morning to capture a new snapshot and pushed it to phone, but snapshot on device stayed the same.

Using 2016 Homey with Firmware 4.2.0.rc 11. Log has been sent direct from app as requested.

Great app otherwise.

**Comment by AdyRock** [comment]
Can you confirm if you have the drop list in the image page set to Motion or Now?
The motion image is only changed when motion is detected and the refresh button is there because I have no control over it and can't hide it.
The Now image is refreshed when you display the device properties, press the refresh button or use the flow action card to update the image.

**Comment by Rockhoppers1964** [comment]
Thank you, no i did not have it set to "Now", and it does update when i do that.
Is there a way to retian the last setting for that function as when you leave and go back into the page it defaults back to "motion".

**Comment by AdyRock** [comment]
Unfortunately, Athom don't give that level of control of the UI so nothing I can do for that one.
